### ISSUE TITLE
Save/load functionality

### ISSUE THREAD

**Issue by Flumble** [viskell/viskell#155]
Viskell definitely requires a way to save and load Viskell programs. The load and save events are available and a basic load/save system is available in the https://github.com/wandernauta/viskell/tree/saveload branch.

**Comment by andrewdavidmackenzie** [comment]
FYI I'm working on this within the current structure.

**Comment by andrewdavidmackenzie** [comment]
I have done a bit of work on this, with some minor changes to the output format and implementing much of the import functionality.

I have it working for a subset of types of blocks - but some others have some complex sub-elements (FunctionInfo, FunctionReference) that I don't understand yet and will need help to serialize and deserialize.

Here are some of my considerations implementing it, and I will share a WIP PR for you to critique.

# Output Formats
I don't see anything wrong with JSON, it's well known, easy to parse and read.

I thought about using GSON "totally" for "automatic" serialization and deserialization.
One problem is that the JSON output would be full of fully qualified classnames and not so nice and clean and easy to read.

That makes it also fragile to package or class name changes. That will be true (at least with class names or object names) for almost any solution.

# Serialization
I've gone the route of adding more data to the export, splitting it into two collections (JSON Arrays) of two different types ("Blocks" and "Connections"). I was going to serialize into three layers as is structured in memory, but saw that addBlock() figures out which layer a block belongs to and adds accordingly. So I can serialize all blocks into one array and deserialization just adds them all using addBlock().

# Deserialization
When I looked more at the code and the need to connect things up after deserialization I decided that deserialization with the help of all the involved objects (like serialization) was probably the best way to go.

There are two main ways I considered to do this:
1) All serializable classes have a default (zero parameter constructor). This is instantiated by the deserializer, then an instance method is called, passing in the Bundle and it sets it own class-specific parameters from the Bundle.

2) All seriablizable classes have a static fromBundleFragment() method that reads in a bundle, and instantiates an object using the existing constructors, reading extra class-specific parameters from the bundle and returns the new object.

I decided on 1) as it was less disruptive, avoiding the need for new Constructors for all classes AND the fromBundle() method - and keeping those constructors in-sync with existing ones. Static method maybe is not so nice, but it's less code and any serialization related changes and limited to this method. It also uses the existing Constructors (some of them have non-trivial logic....)

# Deserialization Process
The input file is read and GSON is used to parse into two arrays, one for Blocks and one for Connections.

For Blocks I have a map of the class simple names to the full class path to be able to find the correct fromBundleFragment() method. This would survive some automatic code refactorings without change.

The Block class has a fromBundle() method that finds the class based on the short classname ("kind") in the JSON, finding the fromBundleFragment() method for the correct sub-class and invoking it, passing it the "properties" sub-Bundle so it can take care of its per-class specific.

Each instantiated Block is then add it to the TopLevelPanel (preserving x and y onscreen).

I keep track of loaded blocks and their IDs (from the export, not the current ID) in a temporary map.

Then, I parse the array of Connections, finding the source Block and sink Block and Anchors from the temporary map. The COnnection is created with the correct source and sink, and then added to the ToplevelPane also.

The Connection and sink Block are then invalidated to force a redraw.

# Other considerations
- Should probably put a version number in the file.
- Could dump the map of object names to class names at the end of the file....but wouldn't help with forwards compatibility and only makes it uglier.
- Needs work on some of the more complex Blocks I don't understand yet.
- Needs unit tests for some of this.

**Comment by andrewdavidmackenzie** [comment]
I think we can close this one in favor of smaller, more specific issues, like https://github.com/viskell/viskell/issues/432 related to remaining issues in deserialization?

**Comment by wandernauta** [comment]
Agreed.
