### ISSUE TITLE
Build fail on javafx symbols

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [viskell/viskell#425]
I'll dig into this and see what I need to do to fix the build on my machine, but comment it here as I suspect it's some missing dependency (JavaFX related) in the maven project?

If I find it, I'll try and do a PR.

> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> [ERROR] /Users/andrew/workspace/viskell/Code/src/main/java/nl/utwente/viskell/ui/components/LambdaBlock.java:[18,28] cannot find symbol
>   symbol:   class TextInputDialog
>   location: package javafx.scene.control
> [ERROR] /Users/andrew/workspace/viskell/Code/src/main/java/nl/utwente/viskell/ui/Main.java:[12,28] cannot find symbol
>   symbol:   class Alert
>   location: package javafx.scene.control
> [ERROR] /Users/andrew/workspace/viskell/Code/src/main/java/nl/utwente/viskell/ui/components/ConstantBlock.java:[5,28] cannot find symbol
>   symbol:   class TextInputDialog
>   location: package javafx.scene.control

**Comment by andrewdavidmackenzie** [comment]
I tried updating my Java8 SDK

/usr/libexec/java_home -v 1.8
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
Andrews-MacBook-Pro:Code andrew$ /usr/libexec/java_home -v 1.8
/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home

But still fails, makes me think maybe that class was removed and I need an *older* JDK?

**Comment by andrewdavidmackenzie** [comment]
Seems this class was added recently in JavaFX 8u40

See https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TextInputDialog.html

I had updated to a Java newer than that (0_73) but my IDE was still referencing an older version of the JDK....and missing this class. Changing that fixed it.

As it's using such a new class, you might want to be more specific about the Java/JavaFX version in the dependencies of the project and/or the maven project.

To know which version of JavaFX you have installed read the javafx.properties file located in your $JAVA_HOME/jre/lib directory.

**Comment by wandernauta** [comment]
You're exactly right, the built-in JavaFX dialogs are a relatively recent addition. In the longer run we'd like to get rid of these dialogs altogether (see #211), but in the meantime I'll add the requirement to the README. Thanks for the heads-up.

**Comment by andrewdavidmackenzie** [comment]
No problem - I was going to PR the docs, but got distracted.

I was thinking of trying to implement the "Open" from file as a first
contribution.....will take some study....does that make sense or are you
moving to new code for all the UI?
