### ISSUE TITLE
File-->New removes blocks, but not all connections

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [viskell/viskell#427]
# Problem
If you do "New", most things are removed, but not all - specifically Connections remains.

# Expected Behavior
After "New" operation, all layers are clear - with no remaining blocks or connections on any.

# Steps to reproduce

1) Create a simple layout like this:
<img width="228" alt="screen shot 2016-03-26 at 16 26 49" src="https://cloud.githubusercontent.com/assets/5529132/14060799/a1bef46a-f36f-11e5-8263-98569e06921e.png">

2) Do "New" operation results in this:

<img width="230" alt="screen shot 2016-03-26 at 16 26 59" src="https://cloud.githubusercontent.com/assets/5529132/14060800/ad06a138-f36f-11e5-945c-65489b2d1066.png">

As you can see from the Inspector, it's not just a visual artifact, Connections remain.

<img width="455" alt="screen shot 2016-03-26 at 16 27 10" src="https://cloud.githubusercontent.com/assets/5529132/14060803/b5b9eed4-f36f-11e5-9d18-f24a490ac9e4.png">

# Code 
ToplevelPane.java 
    public void clearChildren() {
        this.bottomLayer.getChildren().clear();
        this.blockLayer.getChildren().remove(1, this.blockLayer.getChildren().size());
        this.wireLayer.getChildren().remove(1, this.blockLayer.getChildren().size());
        this.attachedBlocks.clear();
    }

I'm not sure why the '1' is there, but it doesn't seem to be the source of the problem.

**Comment by wandernauta** [comment]
Looking at the code, could it be that the second `blockLayer.getChildren().size()` should be `wireLayer` instead?

**Comment by comonoidial** [comment]
That's indeed the problem, now fixed in master.
