### ISSUE TITLE
Deserialization Error: Using the type before it is bound, of binder: val

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [viskell/viskell#432]
There is a problem in deserializing certain block types.

# Reproducing
Reproduce by opening the sample/hello_world.viskell file and observe exception reported to STDERR.

> java.lang.RuntimeException: Using the type before it is bound, of binder: val
> 	at nl.utwente.viskell.haskell.expr.Binder.getBoundType(Binder.java:71)
> 	at nl.utwente.viskell.ui.components.OutputAnchor.getType(OutputAnchor.java:54)
> 	at nl.utwente.viskell.ui.components.Connection.<init>(Connection.java:80)
> 	at nl.utwente.viskell.ui.components.Connection.fromBundle(Connection.java:185)
> 	at nl.utwente.viskell.ui.ToplevelPane.fromBundle(ToplevelPane.java:219)
> 	at nl.utwente.viskell.ui.MenuActions.addChildrenFrom(MenuActions.java:135)
> 	at nl.utwente.viskell.ui.MenuActions.onOpen(MenuActions.java:105)
> 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
> 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
> 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
> 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
> 	at javafx.event.Event.fireEvent(Event.java:198)
> 	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
> 	at com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$20(GlobalMenuAdapter.java:153)
> 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
> 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
> 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
> 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
> 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
> 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
> 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
> 	at javafx.event.Event.fireEvent(Event.java:198)
> 	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
> 	at com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:238)

See FIXME comments in ConstantBlock.java.

> public static ConstantBlock fromBundleFragment(ToplevelPane pane, Map<String,Object> bundleFragment) throws ClassNotFoundException {
>         String value = (String)bundleFragment.get("value");
>         // FIXME Use Environment/TypeBuilder to create Type from String?
>         // FIXME I got lost in the code trying to figure out how to do this isung DataTypeInfo, TypeCon, etc...
>         // FIXME Type type = (String)bundleFragment.get("type");
>         boolean hasValidValue = (Boolean)bundleFragment.get("hasValidValue");
>         return new ConstantBlock(pane, null, value, hasValidValue);
>     }

I don't (yet) know enough about the code to really tackle this one.

**Comment by comonoidial** [comment]
This should be fixed in the current master.

**Comment by andrewdavidmackenzie** [comment]
Did you merge it?
Still fails for me.

**Comment by comonoidial** [comment]
It was resolved in commit https://github.com/viskell/viskell/commit/3e471f838042869f01b4c91bf9d6b724cdca977f to master.
All saved code samples seem to load correctly now.

**Comment by andrewdavidmackenzie** [comment]
Correct. My mistake, hadn't fetched upstream/master
Nice!
