### ISSUE TITLE
Menu can be partly off screen if popped up close to edge

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [viskell/viskell#437]
# Problem
When you click on the background and the tool-bar is popped up, sometimes it is popped-up partially off-screen and some of the options are obscured.

This is worse when the "close" button is one of those that is off-screen, so you can't close it easily.

# Solution
When adding the tool bar to the pane, check if any of the edges are beyond the current viewable area, and if so snap them onto the viewable area.

The corner case where this is impossible (view pane smaller than the tool bar in 1 or 2 dimensions) can just be ignored and the tool bar added as now.

**Comment by comonoidial** [comment]
This make sense to do, however it's minor issue because panning gets you around it.

**Comment by andrewdavidmackenzie** [comment]
Agreed. If panning works for all (see PR pending) then I'll close this.
The only change I'd make is to extend the background pattern to infinity (or a very large number) to avoid the white background when panning....

**Comment by comonoidial** [comment]
With panning working and avoiding obscuring by the top edge, I consider this resolved.
